import { PageTheme } from '@/lib/ui/pageThemes';

const moduleThemeMap: Record<string, PageTheme> = {
  dashboard: 'indigo',
  students: 'indigo',
  'student-transfer': 'indigo',
  teachers: 'indigo',
  classes: 'indigo',
  subjects: 'indigo',
  grades: 'violet',
  exams: 'violet',
  'grade-weight': 'amber',
  'academic-years': 'indigo',
  'academic-reports': 'violet',
  'report-generator': 'violet',
  promotion: 'emerald',
  graduation: 'emerald',
  attendance: 'emerald',
  announcements: 'rose',
  announcement: 'rose',
  notifications: 'rose',
  message: 'rose',
  correspondence: 'rose',
  'guest-book': 'rose',
  'activity-logs': 'slate',
  'data-pokok': 'slate',
  facility: 'amber',
  inventory: 'amber',
  transportation: 'amber',
  cafeteria: 'amber',
  storage: 'cyan',
  infrastructure: 'amber',
  elearning: 'cyan',
  ppdb: 'cyan',
  'card-management': 'cyan',
  hr: 'emerald',
  finance: 'emerald',
  'academic-portal': 'indigo',
  'student-portal': 'indigo',
  events: 'rose',
  alumni: 'indigo',
  library: 'indigo',
  schedules: 'slate',
  settings: 'slate',
  'npsn-change': 'slate',
};

export function getModuleTheme(moduleKey: string, fallback: PageTheme = 'indigo'): PageTheme {
  return moduleThemeMap[moduleKey] ?? fallback;
}
